// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/assidik12/catalyst/config"
	"github.com/assidik12/catalyst/internal/delivery/http/handler"
	"github.com/assidik12/catalyst/internal/delivery/http/middleware"
	"github.com/assidik12/catalyst/internal/delivery/http/route"
	"github.com/assidik12/catalyst/internal/event"
	"github.com/assidik12/catalyst/internal/infrastructure"
	"github.com/assidik12/catalyst/internal/pkg/logger"
	"github.com/assidik12/catalyst/internal/repository/mysql"
	"github.com/assidik12/catalyst/internal/repository/redis"
	"github.com/assidik12/catalyst/internal/service"
	"github.com/assidik12/catalyst/internal/worker"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"log/slog"
	"net/http"
)

// Injectors from injector.go:

func InitializedServer(cfg config.Config) (App, func(), error) {
	db := infrastructure.DatabaseConnection(cfg)
	userRepository := mysql.NewUserRepository(db)
	v := _wireValue
	validate := validator.New(v...)
	string2 := ExtractJwtSecret(cfg)
	userService := service.NewUserService(userRepository, validate, string2)
	userHandler := handler.NewUserHandler(userService)
	productRepository := mysql.NewProductRepository(db)
	client := infrastructure.RedisConnection(cfg)
	wrapper := redis.NewWrapper(client)
	productService := service.NewProductService(productRepository, wrapper, validate)
	productHandler := handler.NewProductHandler(productService)
	transactionRepository := mysql.NewTransactionRepository(db)
	outboxRepository := mysql.NewOutboxRepository(db)
	writer := infrastructure.NewKafkaWriter(cfg)
	kafkaProducer := event.NewKafkaProducer(writer)
	logger := ProvideLogger(cfg)
	transactionService := service.NewTransactionService(transactionRepository, db, validate, userRepository, productRepository, outboxRepository, kafkaProducer, logger)
	transactionHandler := handler.NewTransactionHandler(transactionService)
	aiService := ProvideAIService(cfg)
	aiHandler := handler.NewAIHandler(aiService, productService)
	router := route.NewRouter(userHandler, productHandler, transactionHandler, aiHandler, string2)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := config.NewServer(authMiddleware)
	outboxRelay := worker.NewOutboxRelay(outboxRepository, kafkaProducer, logger)
	app := NewApp(server, outboxRelay)
	return app, func() {
	}, nil
}

var (
	_wireValue = []validator.Option{}
)

// injector.go:

var validatorSet = wire.NewSet(validator.New, wire.Value([]validator.Option{}))

type App struct {
	Server *http.Server
	Relay  worker.OutboxRelay
}

func NewApp(server *http.Server, relay worker.OutboxRelay) App {
	return App{Server: server, Relay: relay}
}

// Setup Kafka
var eventSet = wire.NewSet(infrastructure.NewKafkaWriter, event.NewKafkaProducer, wire.Bind(new(event.Producer), new(*event.KafkaProducer)))

var userSet = wire.NewSet(mysql.NewUserRepository, service.NewUserService, handler.NewUserHandler)

var productSet = wire.NewSet(mysql.NewProductRepository, service.NewProductService, handler.NewProductHandler)

var outboxSet = wire.NewSet(mysql.NewOutboxRepository, worker.NewOutboxRelay)

var transactionSet = wire.NewSet(mysql.NewTransactionRepository, service.NewTransactionService, handler.NewTransactionHandler)

var aiSet = wire.NewSet(
	ProvideAIService, handler.NewAIHandler,
)

func ProvideAIService(cfg config.Config) service.AIService {
	return service.NewOpenAIService(cfg.AIAPIKey, cfg.AIBaseURL, cfg.AIModel)
}

// ProvideLogger initializes slog based on config environment.
func ProvideLogger(cfg config.Config) *slog.Logger {
	return logger.New(cfg.AppEnv)
}

// ExtractJwtSecret extracts the JWT secret from config for Wire to inject into NewUserService.
func ExtractJwtSecret(cfg config.Config) string {
	return cfg.JWTSecret
}
